### ISSUE TITLE
Crash in Emirge amplicon

### ISSUE THREAD

**Issue by ctSkennerton** [csmiller/EMIRGE#15]
Rewrites the reads then dies
```
DONE Rewriting reads with indexes in headers at Thu Apr 18 00:12:57 2013 [0:01:21.308602]...
Number of reads (or read pairs) in input file(s): 3017638
Preallocating reads and quals in memory at Thu Apr 18 00:12:57 2013...
Traceback (most recent call last):
  File "/srv/whitlam/bio/apps/12.04/sw//emirge/0.60/bin/emirge_amplicon.py", line 1543, in <module>
    main()
  File "/srv/whitlam/bio/apps/12.04/sw//emirge/0.60/bin/emirge_amplicon.py", line 1509, in main
    rewrite_reads = not options.no_rewrite_reads)
  File "/srv/whitlam/bio/apps/12.04/sw//emirge/0.60/bin/emirge_amplicon.py", line 221, in __init__
    _emirge.populate_reads_arrays(self)
  File "_emirge_amplicon.pyx", line 525, in _emirge_amplicon.populate_reads_arrays (_emirge_amplicon.c:6577)
IndexError: Out of bounds on buffer access (axis 2)

```

**Comment by ishengtsai** [comment]
Hi,

Is there any update to this? I also have the same error:

Number of reads (or read pairs) in input file(s): 236531
Preallocating reads and quals in memory at Mon Mar 23 14:17:59 2015...
Traceback (most recent call last):
  File "/Users/ishengtsai/bin/EMIRGE/emirge_amplicon.py", line 1576, in <module>
    main()
  File "/Users/ishengtsai/bin/EMIRGE/emirge_amplicon.py", line 1542, in main
    rewrite_reads = not options.no_rewrite_reads)
  File "/Users/ishengtsai/bin/EMIRGE/emirge_amplicon.py", line 221, in __init__
    _emirge.populate_reads_arrays(self)
  File "_emirge_amplicon.pyx", line 525, in _emirge_amplicon.populate_reads_arrays (_emirge_amplicon.c:7016)
    reads[read_index, readtype_index, i] = base_alpha2int(ks_p.seq.s[i])
IndexError: Out of bounds on buffer access (axis 2)

**Comment by csmiller** [comment]
Can you post command line and verify in particular what you passed for maximum read length and what your actual maximum read length was?  I can't replicate this here, but I think this is saying you have a read that is too long for what the code was expecting.

**Comment by f-heeger** [comment]
Look like I have the same problem
My error message is:
> EMIRGE started at Fri Aug  7 16:35:16 2015
> Rewriting reads with indices in headers at Fri Aug  7 16:35:16 2015...
> DONE Rewriting reads with indexes in headers at Fri Aug  7 16:35:19 2015 [0:00:02.404193]...
> Number of reads (or read pairs) in input file(s): 10000
> Preallocating reads and quals in memory at Fri Aug  7 16:35:19 2015...
> Traceback (most recent call last):
>   File "/usr/local/bin/emirge_amplicon.py", line 1576, in <module>
>     main()
>   File "/usr/local/bin/emirge_amplicon.py", line 1542, in main
>     rewrite_reads = not options.no_rewrite_reads)
>   File "/usr/local/bin/emirge_amplicon.py", line 221, in __init__
>     _emirge.populate_reads_arrays(self)
>   File "_emirge_amplicon.pyx", line 525, in _emirge_amplicon.populate_reads_arrays (_emirge_amplicon.c:7033)
> IndexError: Out of bounds on buffer access (axis 2)

My command line was:
> /usr/local/bin/emirge_amplicon.py enirge_assembly -1 CUB_S4_L001_R1_001.sub.fastq -2 CUB_S4_L001_R2_001.sub.fastq -i 550 -s 15 -f db.fasta -b db.fasta_btindex -l 300 -a 6

Any help in dealing with this would be much appreciated. You tool looks like exactly what I need.

**Comment by epruesse** [comment]
Closing due to inactivity. The issue is fixed for Emirge 2, which auto-detects the maximum read-length.
