### ISSUE TITLE
incompatiblility of emirge_rename_fasta.py with new version of biopython?

### ISSUE THREAD

**Issue by rmueller35** [csmiller/EMIRGE#26]
Recently received an error when running the emirge_rename_fasta.py script. 

$ emirge_rename_fasta.py iter.40 > iter.40.cons.rn.fasta
Traceback (most recent call last):
  File "/home/micro/anaconda2/bin/emirge_rename_fasta.py", line 164, in <module>
    main()
  File "/home/micro/anaconda2/bin/emirge_rename_fasta.py", line 159, in main
    rename(wd, options.prob_min, options.record_prefix, options.no_N, options.no_trim_N)
  File "/home/micro/anaconda2/bin/emirge_rename_fasta.py", line 123, in rename
    for prior, record in sorted(sorted_records, reverse=True):
  File "/home/micro/anaconda2/lib/python2.7/site-packages/Bio/SeqRecord.py", line 720, in __eq__
    raise NotImplementedError(_NO_SEQRECORD_COMPARISON)
NotImplementedError: SeqRecord comparison is deliberately not implemented. Explicitly compare the attributes of interest.

**Comment by domenico-simone** [comment]
Hello, 

I get the same problem on some of my samples. Pretty weird since I successfully run the same commands on other samples, with the same features. Any clue?

Thanks
Domenico
