### ISSUE TITLE
IndexError: Out of bounds on buffer access (axis 1)

### ISSUE THREAD

**Issue by rbeinart** [csmiller/EMIRGE#27]
Hi there,
I'm running Emirge on a dataset that keeps getting to iteration 12 and then failing (see below). I saw someone posted about this error previously, and that it had to do with read length, but the comment below said this should not longer be an issue.

Any ideas?

I've run Emirge successfully on other datasets recently, so I'm not sure why this one is a problem.

Thanks!
-Roxanne-

DONE Reading bam file /n/girguis_lab/Users/rbeinart/Emirge/BC_metatranscriptome_Emirge_output/iter.12/bowtie.iter.12.PE.bam at Tue Aug 23 16:21:28
2016 [1:11:31.149570]...
Calculating likelihood (25714, 8320954) for iteration 13 at Tue Aug 23 16:22:47 2016...
        Calculating Pr(N=n) for iteration 13 at Tue Aug 23 16:22:47 2016...
        Loading probN for resume case from /n/girguis_lab/Users/rbeinart/Emirge/
BC_metatranscriptome_Emirge_output/iter.13/probN.pkl
        DONE calculating Pr(N=n) for iteration 13 at Tue Aug 23 16:22:54 2016 [0:00:06.533856]...
Traceback (most recent call last):
  File "/n/girguis_lab/Users/rbeinart/Apps/EMIRGE-master/emirge.py", line 1697, in <module>
    main()
  File "/n/girguis_lab/Users/rbeinart/Apps/EMIRGE-master/emirge.py", line 1688, in main
    do_iterations(em, max_iter = options.iterations, save_every = options.save_every)
  File "/n/girguis_lab/Users/rbeinart/Apps/EMIRGE-master/emirge.py", line 1444, in do_iterations
    os.path.join(subdir, "iter.%02d.cons.fasta"%(em.iteration_i)))
  File "/n/girguis_lab/Users/rbeinart/Apps/EMIRGE-master/emirge.py", line 491, in do_iteration
    self.calc_likelihoods()
  File "/n/girguis_lab/Users/rbeinart/Apps/EMIRGE-master/emirge.py", line 1141, in calc_likelihoods
    lik_data)
  File "_emirge.pyx", line 132, in _emirge._calc_likelihood (_emirge.c:2661)
    s += ( qual2one_minus_p[qualints[i]] * probN_single[pos + i, j] )    # lookup table
IndexError: Out of bounds on buffer access (axis 1)

**Comment by epruesse** [comment]
Hi Roxane,
sorry for the late reply. 
Can you make the input data and parameters you used available to us? It's probably something else than the read length (I assume you already tried running with the max read len parameter set high), but it's much easier to debug and fix with a test case that reproduces it at hand.
Thanks,
Elmar

**Comment by rbeinart** [comment]
No worries, I’ve actually already solved the problem - I have Emirge running on my institution’s HPC (never got it running locally and don’t know why). However, I am curious about the insert size distribution mean and standard deviation - what’s the best way to determine these for a given dataset? For some of my datasets, I’ve already run a “normal” assembly and with IDBA-UD and I can get this information from that run. But for datasets where I want to run Emirge first, is there an easy way to figure this out? 

Thanks!
-Roxanne-

**Comment by epruesse** [comment]
What fixed the problem?

The insert size mean/sd aren't actually very important. They are passed on to bowtie, which uses them to constrain the search. For 16S, setting them high should not change much. You can easily find them by running a bbmap against the 16S reference fasta.

**Comment by domenico-simone** [comment]
Hi @rbeinart , can I ask you what solved the problem? I have the same issue, and I'm running EMIRGE on a HPC cluster too, and read lengths are not an issue since I double-checked them and I set them correctly.

Thanks
Domenico

**Comment by Arkadiy-Garber** [comment]
So still no posted solution to this problem?

**Comment by alouyakis** [comment]
I'm also interested in the solution to this problem.

**Comment by bmaillou** [comment]
I know it has been a while but was the solution ever found. I run into this problem when I restart.  Thanks!
