### ISSUE TITLE
EMIRGE exit without an error message after completing iteration 0. 

### ISSUE THREAD

**Issue by ETaSky** [csmiller/EMIRGE#35]
Hello, I am running emirge on a PE dataset with about 3 million paired end reads. The command I used is:
time emirge.py ../011-Emirge -1 BEI_16SCap_1P.fastq.gz -f ~/Database/EMIRGE/SILVA_128_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta -b ~/Database/EMIRGE/SILVA_128_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed -l 151 -2 BEI_16SCap_2P.fastq -i 375 -s 60 -a 2 --phred33 2>&1 | tee emirge_bei_20170223_2.log

I am running it in a ubuntu virtual machine with 8GB and 4 cores.

The program exit without an error message about 25 minutes after initiating the iteration 1, still at the step [fai_load] build FASTA index. The complete output is attached. The iter.1 folder is empty so I cannot resume the iteration. I used to get emirge working on the clusters my university provided last May.

Thank you very much!
[emirge_bei_20170223_2.txt](https://github.com/csmiller/EMIRGE/files/798204/emirge_bei_20170223_2.txt)

**Comment by ETaSky** [comment]
Hello, I ran emirge on my university cluster and it stopped at the place as when running on my labtop. But this time, I got some error message:
Starting iteration 1 at Thu Feb 23 23:43:58 2017...
Reading bam file /escratch4/jwang01/jwang01_Feb_23/011-EMIRGE/BEI_SCap/iter.00/bowtie.iter.00.PE.bam at Thu Feb 23 23:43:59 2017...
[fai_load] build FASTA index.
Traceback (most recent call last):
  File "/home/jswlab/jwang01/local/emirge/0.60/bin/emirge.py", line 5, in <module>
    pkg_resources.run_script('EMIRGE==0.60.3', 'emirge.py')
  File "/usr/local/bx-python/latest/lib/python/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/bx-python/latest/lib/python/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/panfs/pstor.storage/grphomes/jswlab/jwang01/local/emirge/0.60/lib/python2.7/site-packages/EMIRGE-0.60.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/emirge.py", line 1697, in <module>
    main()
  File "/panfs/pstor.storage/grphomes/jswlab/jwang01/local/emirge/0.60/lib/python2.7/site-packages/EMIRGE-0.60.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/emirge.py", line 1688, in main
    do_iterations(em, max_iter = options.iterations, save_every = options.save_every)
  File "/panfs/pstor.storage/grphomes/jswlab/jwang01/local/emirge/0.60/lib/python2.7/site-packages/EMIRGE-0.60.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/emirge.py", line 1444, in do_iterations
    os.path.join(subdir, "iter.%02d.cons.fasta"%(em.iteration_i)))
  File "/panfs/pstor.storage/grphomes/jswlab/jwang01/local/emirge/0.60/lib/python2.7/site-packages/EMIRGE-0.60.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/emirge.py", line 488, in do_iteration
    self.read_bam(bam_filename, reference_fasta_filename)  # initializes all data structures.
  File "/panfs/pstor.storage/grphomes/jswlab/jwang01/local/emirge/0.60/lib/python2.7/site-packages/EMIRGE-0.60.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/emirge.py", line 269, in read_bam
    self.bamfile_data = numpy.empty((len(predata), 5), dtype=int)
MemoryError

Could anyone help?
Thank you!
