### ISSUE TITLE
IndexError: Out of bounds on buffer access (axis 0)

### ISSUE THREAD

**Issue by Arkadiy-Garber** [csmiller/EMIRGE#38]
> python /home/arkg/EMIRGE/emirge.py emirge-output/ -1 ../../JdF_1362A_J2.573-2/reads/SSU_reads/JdF1362AcombinedSSU.fastq -f SILVA_132_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta -b SILVA_132_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta -l 150 -a 16 -m SSUreadsA.bam.sorted

```
If you use EMIRGE in your work, please cite these manuscripts, as appropriate.

Miller CS, Baker BJ, Thomas BC, Singer SW, Banfield JF (2011)
EMIRGE: reconstruction of full-length ribosomal genes from microbial community short read sequencing data.
Genome biology 12: R44. doi:10.1186/gb-2011-12-5-r44.

Miller CS, Handley KM, Wrighton KC, Frischkorn KR, Thomas BC, Banfield JF (2013)
Short-Read Assembly of Full-Length 16S Amplicons Reveals Bacterial Diversity in Subsurface Sediments.
PloS one 8: e56018. doi:10.1371/journal.pone.0056018.

imported _emirge C functions from: /home/arkg/.cache/Python-Eggs/EMIRGE-0.61.0-py2.7-linux-x86_64.egg-tmp/_emirge.so
Command:
/home/arkg/EMIRGE/emirge.py emirge-output/ -1 ../../JdF_1362A_J2.573-2/reads/SSU_reads/JdF1362AcombinedSSU.fastq -f SILVA_132_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta -b SILVA_132_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta -l 150 -a 16 -m SSUreadsA.bam.sorted

EMIRGE started at Sat Jan 27 17:29:17 2018
Beginning initialization at Sat Jan 27 17:29:17 2018...
Reading bam file /mnt/maximus/data1/chan/arkadiy/Juan_de_Fuca/JdF_1362AB/emirge_SSU/SSUreadsA.bam.sorted at Sat Jan 27 17:29:17 2018...
DONE Reading bam file /mnt/maximus/data1/chan/arkadiy/Juan_de_Fuca/JdF_1362AB/emirge_SSU/SSUreadsA.bam.sorted at Sat Jan 27 17:29:22 2018 [0:00:04.452040]...
DONE with initialization at Sat Jan 27 17:29:22 2018...
Starting iteration 0 at Sat Jan 27 17:29:22 2018...
Reading bam file /mnt/maximus/data1/chan/arkadiy/Juan_de_Fuca/JdF_1362AB/emirge_SSU/SSUreadsA.bam.sorted at Sat Jan 27 17:29:22 2018...
DONE Reading bam file /mnt/maximus/data1/chan/arkadiy/Juan_de_Fuca/JdF_1362AB/emirge_SSU/SSUreadsA.bam.sorted at Sat Jan 27 17:29:25 2018 [0:00:03.364967]...
Calculating likelihood (1041, 42776) for iteration 0 at Sat Jan 27 17:29:25 2018...
	Calculating Pr(N=n) for iteration 0 at Sat Jan 27 17:29:25 2018...
	DONE calculating Pr(N=n) for iteration 0 at Sat Jan 27 17:29:26 2018 [0:00:01.241517]...
Traceback (most recent call last):
  File "/home/arkg/EMIRGE/emirge.py", line 1697, in <module>
    main()
  File "/home/arkg/EMIRGE/emirge.py", line 1688, in main
    do_iterations(em, max_iter = options.iterations, save_every = options.save_every)
  File "/home/arkg/EMIRGE/emirge.py", line 1439, in do_iterations
    em.do_iteration(em.current_bam_filename, em.current_reference_fasta_filename)
  File "/home/arkg/EMIRGE/emirge.py", line 491, in do_iteration
    self.calc_likelihoods()
  File "/home/arkg/EMIRGE/emirge.py", line 1141, in calc_likelihoods
    lik_data)
  File "_emirge.pyx", line 130, in _emirge._calc_likelihood
    if numeric_bases[i] == j:   # this is called base, set 1-P
IndexError: Out of bounds on buffer access (axis 0)
```

I am running on SSU reads pulled out from the raw quality reads using sortmerna. These include read pairs combined and uncombined with flash

**Comment by Arkadiy-Garber** [comment]
Thanks in advance!
